sudo: required
language: node_js
services:
  - docker
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install:
  - npm install -g bower
install:
  - npm install
  - bower install
before_script:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.8.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
script:
  - npm run build
  - docker build -t blimpify/web .
after_success:
after_failure:
before_deploy:
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
after_deploy:
after_script: